version: '2'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - rabbitmq

  insider_transaction:
    build:
      context: ./insider_transaction
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      
  insider_transaction_beat:
    build:
      context: ./insider_transaction
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    entrypoint: celery
    command:  -A insider_transaction beat --config=celeryconfig
      
  earning:
    build:
      context: ./earning
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      
  stock_price:
    build:
      context: ./stock_price
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      
  flower:
    build:
      context: ./flower
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5555:5555"
    depends_on:
      - rabbitmq

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"